//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamNET.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExamNETResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExamNETResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExamNET.Resources.ExamNETResource", typeof(ExamNETResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISYLABLLE.
        /// </summary>
        public static string DISYLABLLE {
            get {
                return ResourceManager.GetString("DISYLABLLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eight.
        /// </summary>
        public static string Eight {
            get {
                return ResourceManager.GetString("Eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Five.
        /// </summary>
        public static string Five {
            get {
                return ResourceManager.GetString("Five", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four.
        /// </summary>
        public static string Four {
            get {
                return ResourceManager.GetString("Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Luck :).
        /// </summary>
        public static string GoodLuck {
            get {
                return ResourceManager.GetString("GoodLuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hundred.
        /// </summary>
        public static string Hundred {
            get {
                return ResourceManager.GetString("Hundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hundreds.
        /// </summary>
        public static string Hundreds {
            get {
                return ResourceManager.GetString("Hundreds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MATHEMATICS.
        /// </summary>
        public static string MATHEMATICS {
            get {
                return ResourceManager.GetString("MATHEMATICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MATHEMATICS_DECOMPOSE.
        /// </summary>
        public static string MATHEMATICS_DECOMPOSE {
            get {
                return ResourceManager.GetString("MATHEMATICS_DECOMPOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MATHEMATICS_DICTATION.
        /// </summary>
        public static string MATHEMATICS_DICTATION {
            get {
                return ResourceManager.GetString("MATHEMATICS_DICTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MATHEMATICS_FOUR_OPERATIONS.
        /// </summary>
        public static string MATHEMATICS_FOUR_OPERATIONS {
            get {
                return ResourceManager.GetString("MATHEMATICS_FOUR_OPERATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MATHEMATICS_LOGIC {
            get {
                return ResourceManager.GetString("MATHEMATICS_LOGIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MATHEMATICS_PREDECESSOR_SUCCESSOR.
        /// </summary>
        public static string MATHEMATICS_PREDECESSOR_SUCCESSOR {
            get {
                return ResourceManager.GetString("MATHEMATICS_PREDECESSOR_SUCCESSOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MATHEMATICS_WRITE_EXTENSE.
        /// </summary>
        public static string MATHEMATICS_WRITE_EXTENSE {
            get {
                return ResourceManager.GetString("MATHEMATICS_WRITE_EXTENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MATHEMATICS_WRITE_NUMBER {
            get {
                return ResourceManager.GetString("MATHEMATICS_WRITE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONOSYLABLLE.
        /// </summary>
        public static string MONOSYLABLLE {
            get {
                return ResourceManager.GetString("MONOSYLABLLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine.
        /// </summary>
        public static string Nine {
            get {
                return ResourceManager.GetString("Nine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One.
        /// </summary>
        public static string One {
            get {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one.
        /// </summary>
        public static string OneThousand {
            get {
                return ResourceManager.GetString("OneThousand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal response.
        /// </summary>
        public static string PersonalResponse {
            get {
                return ResourceManager.GetString("PersonalResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POLYSYLABLLE.
        /// </summary>
        public static string POLYSYLABLLE {
            get {
                return ResourceManager.GetString("POLYSYLABLLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORTUGUESE.
        /// </summary>
        public static string PORTUGUESE {
            get {
                return ResourceManager.GetString("PORTUGUESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORTUGUESE_ANTONYMS.
        /// </summary>
        public static string PORTUGUESE_ANTONYMS {
            get {
                return ResourceManager.GetString("PORTUGUESE_ANTONYMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORTUGUESE_CONSONANT_CLUSTERS.
        /// </summary>
        public static string PORTUGUESE_CONSONANT_CLUSTERS {
            get {
                return ResourceManager.GetString("PORTUGUESE_CONSONANT_CLUSTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORTUGUESE_CREATE_PHRASES.
        /// </summary>
        public static string PORTUGUESE_CREATE_PHRASES {
            get {
                return ResourceManager.GetString("PORTUGUESE_CREATE_PHRASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORTUGUESE_DICTATION.
        /// </summary>
        public static string PORTUGUESE_DICTATION {
            get {
                return ResourceManager.GetString("PORTUGUESE_DICTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORTUGUESE_SEPARATE_SYLLABLES.
        /// </summary>
        public static string PORTUGUESE_SEPARATE_SYLLABLES {
            get {
                return ResourceManager.GetString("PORTUGUESE_SEPARATE_SYLLABLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professor.
        /// </summary>
        public static string Professor {
            get {
                return ResourceManager.GetString("Professor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven.
        /// </summary>
        public static string Seven {
            get {
                return ResourceManager.GetString("Seven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimpleTextDiv.
        /// </summary>
        public static string SimpleTextDiv {
            get {
                return ResourceManager.GetString("SimpleTextDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimpleTextMult.
        /// </summary>
        public static string SimpleTextMult {
            get {
                return ResourceManager.GetString("SimpleTextMult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Six.
        /// </summary>
        public static string Six {
            get {
                return ResourceManager.GetString("Six", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten.
        /// </summary>
        public static string Ten {
            get {
                return ResourceManager.GetString("Ten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tens.
        /// </summary>
        public static string Tens {
            get {
                return ResourceManager.GetString("Tens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thousand.
        /// </summary>
        public static string Thousand {
            get {
                return ResourceManager.GetString("Thousand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thousands.
        /// </summary>
        public static string Thousands {
            get {
                return ResourceManager.GetString("Thousands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three.
        /// </summary>
        public static string Three {
            get {
                return ResourceManager.GetString("Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRISYLABLLE.
        /// </summary>
        public static string TRISYLABLLE {
            get {
                return ResourceManager.GetString("TRISYLABLLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two.
        /// </summary>
        public static string Two {
            get {
                return ResourceManager.GetString("Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to two.
        /// </summary>
        public static string TwoThousand {
            get {
                return ResourceManager.GetString("TwoThousand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
    }
}
