//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamNET.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExamNETResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExamNETResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExamNET.Resources.ExamNETResource", typeof(ExamNETResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISYLABLLE.
        /// </summary>
        public static string DISYLABLLE {
            get {
                return ResourceManager.GetString("DISYLABLLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Luck :).
        /// </summary>
        public static string GoodLuck {
            get {
                return ResourceManager.GetString("GoodLuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MATHEMATICS.
        /// </summary>
        public static string MATHEMATICS {
            get {
                return ResourceManager.GetString("MATHEMATICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MATHEMATICS_DICTATION.
        /// </summary>
        public static string MATHEMATICS_DICTATION {
            get {
                return ResourceManager.GetString("MATHEMATICS_DICTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONOSYLABLLE.
        /// </summary>
        public static string MONOSYLABLLE {
            get {
                return ResourceManager.GetString("MONOSYLABLLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal response.
        /// </summary>
        public static string PersonalResponse {
            get {
                return ResourceManager.GetString("PersonalResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POLYSYLABLLE.
        /// </summary>
        public static string POLYSYLABLLE {
            get {
                return ResourceManager.GetString("POLYSYLABLLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORTUGUESE.
        /// </summary>
        public static string PORTUGUESE {
            get {
                return ResourceManager.GetString("PORTUGUESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORTUGUESE_ANTONYMS.
        /// </summary>
        public static string PORTUGUESE_ANTONYMS {
            get {
                return ResourceManager.GetString("PORTUGUESE_ANTONYMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORTUGUESE_CONSONANT_CLUSTERS.
        /// </summary>
        public static string PORTUGUESE_CONSONANT_CLUSTERS {
            get {
                return ResourceManager.GetString("PORTUGUESE_CONSONANT_CLUSTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORTUGUESE_CREATE_PHRASES.
        /// </summary>
        public static string PORTUGUESE_CREATE_PHRASES {
            get {
                return ResourceManager.GetString("PORTUGUESE_CREATE_PHRASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORTUGUESE_DICTATION.
        /// </summary>
        public static string PORTUGUESE_DICTATION {
            get {
                return ResourceManager.GetString("PORTUGUESE_DICTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORTUGUESE_SEPARATE_SYLLABLES.
        /// </summary>
        public static string PORTUGUESE_SEPARATE_SYLLABLES {
            get {
                return ResourceManager.GetString("PORTUGUESE_SEPARATE_SYLLABLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professor.
        /// </summary>
        public static string Professor {
            get {
                return ResourceManager.GetString("Professor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRISYLABLLE.
        /// </summary>
        public static string TRISYLABLLE {
            get {
                return ResourceManager.GetString("TRISYLABLLE", resourceCulture);
            }
        }
    }
}
